config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/auth/spotify/callback', to: 'users#spotify'

  resources :venues, only: [:index, :show] do
    resources :venue_tracks_playeds, only: [ :create ]
    resources :events, only: [ :new, :create]
  end
  resources :events, only: [:show ] do
    resources :requests, only: [ :index ]
    resources :tracks, only: [:show] do
      resources :requests, only: [ :create]

  end
end

  resources :event_tracks, only: [:update]
  resources :requests, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  belongs_to :user
  has_many :event_tracks, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :tracks, through: :event_tracks
  has_many :requested_tracks, through: :requests, source: :tracks
  has_one_attached :photo
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :show ]

    def show
      @event = Event.find(params[:id])

    if user_signed_in?
      if params[:query].present?
        @tracks = Track.joins(:event_tracks).where(event_tracks: { event_id: @event.id }).select('tracks.*').order(:already_played).where("artist @@ :query OR name @@ :query", query: "%#{params[:query]}%")
        @requested_tracks = Track.joins(:requests).where(requests: { event_id: @event.id }).where(requests: { user_id: current_user.id }).select('tracks.*').where("artist @@ :query OR name @@ :query", query: "%#{params[:query]}%")
        @played_tracks = Track.joins(:event_tracks).where(event_tracks: { already_played: true }).where(event_tracks: { event_id: @event.id }).select('tracks.*').where("artist @@ :query OR name @@ :query", query: "%#{params[:query]}%")
      else
        @tracks = Track.joins(:event_tracks).where(event_tracks: { event_id: @event.id }).select('tracks.*').order(:already_played)
        @requested_tracks = Track.joins(:requests, :event_tracks).where(requests: { event_id: @event.id }).where(requests: { user_id: current_user.id }).select('tracks.*').order(:already_played)
        @played_tracks = Track.joins(:event_tracks).where(event_tracks: { already_played: true }).where(event_tracks: { event_id: @event.id }).select('tracks.*')
      end

      @track_request_count = Track.joins(:requests).where(requests: { event_id: @event.id }).group('tracks.id').count
      @track_request_count = @track_request_count.sort_by {|_k, v| -v}.to_h
      else
        redirect_to new_user_session_path
      end
    end

    def new
      @event = Event.new
      @venue = Venue.find(params[:venue_id])
    end

    def create
      @event = Event.new(event_params)
      @event.user = current_user
      @venue = Venue.find(params[:venue_id])
      @event.venue = @venue
      @event.save
      redirect_to venue_path(@venue)
    end

    private

    def event_params
      params.require(:event).permit(:name, :date)
    end
end

app/views/events/_photo.html.erb
<div class="img-background">
    <%= image_tag event.photo %>
</div>

app/views/events/new.html.erb
<div class="container pt-2">
  <%= simple_form_for [@venue, @event] do |f| %>
  <h5><%= f.input :name %></h5>
  <h6><%= f.input :date %></h6>
  <%= f.button :submit, class: "btn create-button" %>
  <% end %>

<!-- link_to "Back", ??  -->
</div>

app/views/events/show.html.erb
<%= render 'shared/navbar_eventtracks' %>
<div class="bg-white">
<div class="d-flex">
    <div class="make-black mx-4 mt-2">
       <%= link_to venue_path(@event.venue) do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
    </div>
</div>

<% if @event.user == current_user %>
  <h5 class=" text-center mb-2">DJ DASHBOARD</h5>

      <p class="text-right pt-4 pr-3"><span class="text-background p-1 m-1"><em> Press to mark as played </em></span><span class="request-button"><i class="far fa-check-square"></i></span></p>
  <%# raise %>
    <% @track_request_count.each do |track_id, count| %>
    <% track = Track.find(track_id) %>
    <% unless @event.event_tracks.find_by(track: track).already_played %>
      <div class="song-card">
        <div class="d-flex m-2">
          <%=cl_image_tag track.photo.key, height: 100, width: 100, crop: :scale %>
            <div class="align-self-center m-3">
              <h4 class="m-0"><%= track.name %> </h4>
              <p class="m-0"><%= track.artist %></p>
              <p class="m-0 genre"><%= track.genre.capitalize %></p>
            </div>

          <p class="card-request mr-2"><span class="increase-text"><strong><%= count %></strong></span> request(s)</p>

          <div class="ml-auto align-self-center">
                  <div class="ml-auto align-self-center request-button">
                    <%= link_to "/event_tracks/#{EventTrack.where(track_id: track.id).where(event_id: @event.id)[0].id}", method: :patch do %>
                      <i class="far fa-check-square"></i>
                    <% end %>
                  </div>
          </div>
        </div>
      </div>
     <% end %>
  <% end %>

<% else %>


  <div class="d-flex justify-content-center text-center">
    <%= form_tag event_path, class: "search-tracks",  method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search-field-tracks justify-content-center",
      placeholder: "  Search artist/track"
    %>
    <%= button_tag :submit, class: "create-button-tracks" do %>
      <i class="fas fa-search"></i>
    <% end %>
    <% end %>
  </div>


  <nav>
    <div class="nav request-nav nav-tabs mt-2" id="nav-tab" role="tablist">
      <a class="nav-item request-nav-item nav-link active" id="nav-all-tab" data-toggle="tab" href="#nav-all" role="tab" aria-controls="nav-all" aria-selected="true">All songs</a>
      <a class="nav-item request-nav-item nav-link" id="nav-played-tab" data-toggle="tab" href="#nav-played" role="tab" aria-controls="nav-played" aria-selected="false">Played</a>
      <a class="nav-item request-nav-item nav-link" id="nav-requested-tab" data-toggle="tab" href="#nav-requested" role="tab" aria-controls="nav-requested" aria-selected="false">Requested</a>
    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-all" role="tabpanel" aria-labelledby="nav-all-tab">
      <p class="text-right pt-4 pr-3"><span class="text-background p-1 m-1"><em> Press icon to request your song </em></span><span class="request-button"><i class="fas fa-arrow-alt-circle-up"></i></span></p>
      <% @tracks.each do |track| %>
        <% if @event.event_tracks.find_by(track: track).already_played %>
          <div class="song-card make-grey">
        <% else %>
          <div class="song-card">
        <% end %>
            <div class="d-flex m-2">
              <%=cl_image_tag track.photo.key, height: 100, width: 100, crop: :scale %>
              <div class="align-self-center m-3">
                <h4 class="m-0"><%= track.name %> </h4>
                <p class="m-0"><%= track.artist %></p>
                <p class="m-0 genre"><%= track.genre.capitalize %></p>
              </div>


              <% unless @event.event_tracks.find_by(track: track).already_played %>
                <% if Request.where(track_id: track.id).where(event_id: @event.id).where(user_id: current_user.id)[0] %>


                  <i class="card-request">Requested</i>

                    <div class="ml-auto align-self-center request-button-trash">
                    <%= link_to request_path(Request.where(track_id: track.id).where(event_id: @event.id).where(user_id: current_user.id)[0].id), method: :delete do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                    </div>

                <% else %>
                  <div class="ml-auto align-self-center request-button">
                    <%= link_to event_track_requests_path(@event, track), method: :create do %>
                      <i class="fas fa-arrow-alt-circle-up"></i>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
        </div>
      <% end %>
    </div>

    <div class="tab-pane fade" id="nav-played" role="tabpanel" aria-labelledby="nav-played-tab">
      <% @played_tracks.each do |track| %>
          <div class="song-card make-grey">
            <div class="d-flex m-2">
              <%=cl_image_tag track.photo.key, height: 100, width: 100, crop: :scale %>
              <div class="align-self-center m-3">
                <h4 class="m-0"><%= track.name %> </h4>
                <p class="m-0"><%= track.artist %></p>
                <p class="m-0 genre"><%= track.genre.capitalize %></p>
              </div>
            </div>
          </div>
      <% end %>
    </div>

    <div class="tab-pane fade" id="nav-requested" role="tabpanel" aria-labelledby="nav-requested-tab">
      <% @requested_tracks.each do |track| %>
        <% if @event.event_tracks.find_by(track_id: track.id).already_played %>
          <div class="song-card make-grey">
        <% else %>
          <div class="song-card">
        <% end %>
            <div class="d-flex m-2">
              <%=cl_image_tag track.photo.key, height: 100, width: 100, crop: :scale %>
              <div class="align-self-center m-3">
                <h4 class="m-0"><%= track.name %> </h4>
                <p class="m-0"><%= track.artist %></p>
                <p class="m-0 genre"><%= track.genre.capitalize %></p>
              </div>


              <% unless @event.event_tracks.find_by(track: track).already_played %>
                <% if Request.where(track_id: track.id).where(event_id: @event.id).where(user_id: current_user.id)[0] %>
                  <div class="ml-auto align-self-center">
                    <i class="card-request mr-2">Requested</i>
                    <div class="ml-auto align-self-center request-button-trash">
                    <%= link_to request_path(Request.where(track_id: track.id).where(event_id: @event.id).where(user_id: current_user.id)[0].id), method: :delete do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
</div>