config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/auth/spotify/callback', to: 'users#spotify'

  resources :venues, only: [:index, :show] do
    resources :venue_tracks_playeds, only: [ :create ]
    resources :events, only: [ :new, :create]
  end
  resources :events, only: [:show ] do
    resources :requests, only: [ :index ]
    resources :tracks, only: [:show] do
      resources :requests, only: [ :create]

  end
end

  resources :event_tracks, only: [:update]
  resources :requests, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
class Venue < ApplicationRecord
  # include PgSearch::Model
  # pg_search_scope :search_by_name_and_location,
  #   against: [ :location, :name ],
  #   using: {
  #     tsearch: { prefix: true } # <-- now `superman batm` will return something!
  #   }
  has_many :events, dependent: :destroy
  has_many :venue_tracks_played, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_one_attached :photo
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    # if params[:query].present?
    #   @venues = Venue.where("location @@ :query OR venue_name @@ :query", query: "%#{params[:query]}%")
    # else
    #   @venues = Venue.all
    # end


    #   @venues = Venue.geocoded

    #   @markers = @venues.map do |venue|
    #     {
    #       lat: venue.latitude,
    #       lng: venue.longitude,
    #       infoWindow: render_to_string(partial: "info_window", locals: { venue: venue })
    #     }
    #   end
    # end

      # if @venues = Venue.search_by_name_and_location(params[:query])
      # else
      #   @venues = @venues = Venue.near("#{params[:query]}")
      # # @venues = Venue.where("location @@ :query", query: "%#{params[:query]}%")
      # end

      @venues = Venue.near("#{params[:query]}")

      @geo_venues = @venues.geocoded

      @markers = @geo_venues.map do |geo_venue|
      {
        lat: geo_venue.latitude,
        lng: geo_venue.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { venue: geo_venue }),
        style: geo_venue.club ? "marker2" : "marker1"
      }
      end
    end

    def show
      # session[:search_results] = request.url

      if user_signed_in?
        @venue = Venue.find(params[:id])
        @events = @venue.events
        # @playlist_code = @venue.playlist_id
        @playlist_code = '4TaOLNlPlYlcPb2VxBPlkR'
        @playlist = RSpotify::Playlist.find_by_id(@playlist_code)
        # track_artist = @playlist.tracks.first.artists[0].name


        if params[:query].present?
          @tracks = @playlist.tracks.select { |track| track.name.include?(params[:query].capitalize) || track.artists.first.name.include?(params[:query].capitalize) }
        else
           @tracks = @playlist.tracks
        end
      else
        redirect_to new_user_session_path
      end
    end
end

app/views/venues/_info_window.html.erb
<div class="container rounded">
  <%= link_to venue_path(venue) do %>
    <div class="img-background rounded">
      <%=cl_image_tag venue.photo.key %>
    </div>
    <div class="link-darken">
      <h6 class="pt-2"></i> <%= venue.name.upcase %></h6>
      <p><i class="fas fa-map-marker-alt"></i> <%= venue.location %></p>
    </div>
    <% end %>
</div>

app/views/venues/show.html.erb
<%= render 'shared/navbar_events' %>



<div class="bg-white px-3">

<!-- <div class="d-flex">
    <div class="make-black mx-4 mt-2">
      <%= link_to root_path do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
    </div>
</div>
 -->

  <% if @venue.club %>

    <div class="event-nav">


          <div class="event-nav-item make-black pt-3">
             <%= link_to venues_path(:query => @venue.location) do %>
              <i class="fas fa-chevron-left"></i>
            <% end %>
          </div>

         <div class="event-nav-item text-center pt-2">
      <h5 class="pt-2">EVENT LIST</h5>
      </div>


        <div class="event-nav-item d-flex justify-content-end">
        <div class="btn add-new link-whiten">
          <%= link_to "+", new_venue_event_path(@venue) %>
        </div>
      </div>

    </div>


    <div class="row">
      <% @events.each do |event| %>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
          <div class="card-product flex-container space-between m-3 p-3">
            <%= link_to "", event_path(event), class: "card-link"%>

              <%= cl_image_tag event.photo.key, height: 150, width: 80, crop: :scale %>

              <div class="card-product-infos mt-3">
                <h4><%= event.name %></h4>
                <p><i class="fas fa-music"></i> <%= Event.find(event.id).user.dj_name %></p>
                <p><i class="fas fa-house-user"></i> <%= Event.find(event.id).venue.name %></p>

              <!-- <div class="flex-container"> -->
              <!--  <div class="card-date"> -->
                  <p><i class="far fa-calendar-alt"></i> <%= event.date.strftime("%d %b") %></p>
                <!--  <p><%= event.date.strftime("%b") %></p> -->
              <!--  </div> -->
              <!-- </div> -->
              </div>
          </div>
        </div>
      <% end %>
    </div>

    <% else %>

     <div class="d-flex">
        <div class="make-black mx-4 mt-2">
            <%= link_to venues_path(:query => @venue.location) do %>
            <i class="fas fa-chevron-left"></i>
          <% end %>
        </div>
      </div>

    <span id="hidden_token" style="display:none"></span>

    <p class="pb-2"> </p>
      <div class="song-card-play pt-3 make-purple">
        <div class="d-flex mb-3 m-3">
          <img src="" alt="Currently Playing" id="current-image" width="100" height="100">
          <div class="align-self-center m-3">
            <h4 id="current-playing-title"><em>Title</em></h4>
            <p id="current-playing-artist"><em>Artist</em></p>
          </div>
          <p class="card-request mr-2"><em>Playing Now<span class="request-button-black"></em><i class="fas fa-play-circle"></i></span></p>
        </div>
    </div>


    <div class="d-flex justify-content-center text-center">
    <%= form_tag venue_path, class: "search-tracks",  method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search-field-tracks justify-content-center",
      placeholder: "  Search artist/track"
    %>
    <%= button_tag :submit, class: "create-button-tracks" do %>
      <i class="fas fa-search"></i>
    <% end %>
    <% end %>
  </div>

  <p class="text-right pt-1 pr-3"><span class="text-background p-1 m-1"><em> Press to add song to queue </em></span><span class="request-button"><i class="fas fa-arrow-alt-circle-up"></i></span></p>


    <% @tracks.each do |track| %>

    <% if !VenueTracksPlayed.find_by({ track_id: track.id, venue_id: @venue.id }) %>
      <div class="song-card">
        <div id="myDIV">
        <div class="d-flex m-2">

          <% if track.album.images %>

            <%=image_tag(track.album.images.first["url"], height: 100, width: 100, crop: :scale  )%>

            <% elsif track.artists.first.images %>

              <%=image_tag(track.album.images.first["url"], height: 100, width: 100, crop: :scale  )%>

            <% else %>

              <%=image_tag('singer.jpg', height: 100, width: 100, crop: :scale  )%>

          <% end %>
          <div class="align-self-center m-3">
            <h4 class="m-0"><%= track.name %> </h4>
            <p class="m-0"><%= track.artists.first.name %></p>
          </div>

          <div type= "button" id="request-new" class="ml-auto align-self-center request-button" data-toggle="modal" data-target="#exampleModal<%= track.id %>">
              <i class="fas fa-arrow-alt-circle-up"></i>
          </div>
          <div class="modal fade mt-5" id="exampleModal<%= track.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Song Selection</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                   <div class="d-flex m-2">
                    <% if track.album.images %>

                      <%=image_tag(track.album.images.first["url"], height: 100, width: 100, crop: :scale  )%>

                      <% elsif track.artists.first.images %>

                        <%=image_tag(track.album.images.first["url"], height: 100, width: 100, crop: :scale  )%>

                      <% else %>

                        <%=image_tag('singer.jpg', height: 100, width: 100, crop: :scale  )%>

                    <% end %>
                  <div class="align-self-center m-3">
                    <h4 class="m-0"><%= track.name %> </h4>
                    <p class="m-0"><%= track.artists.first.name %></p>
                    <p id="added-queue"> </p>
                  </div>
                </div>
                </div>
                <div class="modal-footer">
                  <div type="button" class="back-button" data-dismiss="modal">Back</div>

                  <%= link_to venue_venue_tracks_playeds_path(@venue, track_id: track.id), method: :create, data: { confirm: "Confirmed!" } do %>
                  <div type="button" class="request-button-confirm confirm-add" onclick="" data-dismiss="modal"> <h6 class="pt-2">ADD TO QUEUE</h6>
                  <span class="track-id" style="display:none"><%= track.external_urls["spotify"] %></span>
                  </div>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      <% else %>
      <div class="song-card make-grey">
        <div id="myDIV">
        <div class="d-flex m-2">

          <% if track.album.images %>

            <%=image_tag(track.album.images.first["url"], height: 100, width: 100, crop: :scale  )%>

            <% elsif track.artists.first.images %>

              <%=image_tag(track.album.images.first["url"], height: 100, width: 100, crop: :scale  )%>

            <% else %>

              <%=image_tag('singer.jpg', height: 100, width: 100, crop: :scale  )%>

          <% end %>

              <div class="align-self-center m-3">
                <h4 class="m-0"><%= track.name %> </h4>
                <p class="m-0"><%= track.artists.first.name %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

<% content_for :meta_title, "#{@venue.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @venue.location %>
<% content_for :meta_image, cl_image_path(@venue.photo.key) %>